export const courses = [
  {
    id: "1",
    title: "交通問路與搭乘方式 Asking Directions & Transportation",
    description: "學習如何用英文問路以及搭乘大眾運輸工具的相關用語。",
    thumbnail: "https://img.youtube.com/vi/8yr5zzOfNz0/maxresdefault.jpg",
    videoId: "8yr5zzOfNz0",
    duration: "8:35",
    level: "Beginner",
    tags: ["Travel", "Daily Life"],
    progress: 0,
  },
  {
    id: "2",
    title: "聊聊最喜歡的科目 Talking About Favorite Subjects",
    description: "學習如何用英文討論學校科目以及表達喜好。",
    thumbnail: "https://img.youtube.com/vi/bqrpXfzCTUw/maxresdefault.jpg",
    videoId: "bqrpXfzCTUw",
    duration: "11:09",
    level: "Beginner",
    tags: ["School", "Conversation"],
    progress: 0,
  },
  {
    id: "3",
    title: "聊聊最喜歡的科目 (Part 2)",
    description: "深入探討學校生活與科目喜好的對話練習。",
    thumbnail: "https://img.youtube.com/vi/FhHQu8y_3c0/maxresdefault.jpg",
    videoId: "FhHQu8y_3c0",
    duration: "9:49",
    level: "Beginner",
    tags: ["School", "Conversation"],
    progress: 0,
  },
];
